ALTER TABLE game_account.game_user ADD expired_at DATETIME DEFAULT '2199-01-01 00:00:00' NOT NULL ;
INSERT INTO `game_type` (`pkid`, `created_at`, `updated_at`, `type_name`, `type_desc`) VALUES (NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'mj-baida', '麻将BD'), (NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'pk-pinshi', '扑克PS');
INSERT INTO `game_user_priv` (`pkid`, `created_at`, `updated_at`, `user_pkid`, `priv_item`, `game_type_pkid`) VALUES (NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', 'all', '1'), (NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '1', 'all', '2');
ALTER TABLE `game_info` ADD `game_type_pkid` INT(10) UNSIGNED NULL, ADD `user_pkid` INT(10) UNSIGNED NULL AFTER `game_type_pkid`;
ALTER TABLE `game_result` ADD `game_type_pkid` INT(10) UNSIGNED NULL, ADD `user_pkid` INT(10) UNSIGNED NULL AFTER `game_type_pkid`;
ALTER TABLE `game_close_bill_history_game` ADD `game_type_pkid` INT(10) UNSIGNED NULL, ADD `user_pkid` INT(10) UNSIGNED NULL AFTER `game_type_pkid`;
ALTER TABLE `game_close_bill_history_detail` ADD `game_type_pkid` INT(10) UNSIGNED NULL, ADD `user_pkid` INT(10) UNSIGNED NULL AFTER `game_type_pkid`;
ALTER TABLE `game_close_bill_history` ADD `game_type_pkid` INT(10) UNSIGNED NULL, ADD `user_pkid` INT(10) UNSIGNED NULL AFTER `game_type_pkid`;
UPDATE `game_info` SET user_pkid=1,game_type_pkid=1;
UPDATE `game_result` SET user_pkid=1,game_type_pkid=1;
UPDATE `game_close_bill_history_game` SET user_pkid=1,game_type_pkid=1;
UPDATE `game_close_bill_history_detail` SET user_pkid=1,game_type_pkid=1;
UPDATE `game_close_bill_history` SET user_pkid=1,game_type_pkid=1;
ALTER TABLE game_account.game_type ADD most_player_count INT DEFAULT 0 NOT NULL ;
